# Generated by Django 3.0.7 on 2020-11-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
